In [10]:
import pandas as pd

In [11]:
path_pt1 = "C:\\Users\\Raquel Marques\\Desktop\\Ironhack\\Second Project\\df_final_web_data_pt_1.txt"

path_pt2 = "C:\\Users\\Raquel Marques\\Desktop\\Ironhack\\Second Project\\df_final_web_data_pt_2.txt"

In [12]:
df_web1 = pd.read_csv(path_pt1, sep=",")

df_web2 = pd.read_csv(path_pt2, sep=",")

##### Merge both parts into one DataFrame

In [13]:
df_web = pd.concat([df_web1, df_web2], ignore_index=True)

print("Dataset 1:", df_web1.shape)
print("Dataset 2:", df_web2.shape)
print("Merged dataset:", df_web.shape)

Dataset 1: (343141, 5)
Dataset 2: (412264, 5)
Merged dataset: (755405, 5)

#### First Analysis

- First rows

In [ ]:
display(df_web.head())

,client_id,visitor_id,visit_id,process_step,date_time
0,9988021,580560515_7732621733,781255054_21935453173_531117,step_3,2017-04-17 15:27:07
1,9988021,580560515_7732621733,781255054_21935453173_531117,step_2,2017-04-17 15:26:51
2,9988021,580560515_7732621733,781255054_21935453173_531117,step_3,2017-04-17 15:19:22
3,9988021,580560515_7732621733,781255054_21935453173_531117,step_2,2017-04-17 15:19:13
4,9988021,580560515_7732621733,781255054_21935453173_531117,step_3,2017-04-17 15:18:04

- Column names

In [14]:
print(df_web.columns)

Index(['client_id', 'visitor_id', 'visit_id', 'process_step', 'date_time'], dtype='str')

- Data types and non-null values

In [15]:
df_web.info()

<class 'pandas.DataFrame'>
RangeIndex: 755405 entries, 0 to 755404
Data columns (total 5 columns):
 #   Column        Non-Null Count   Dtype
---  ------        --------------   -----
 0   client_id     755405 non-null  int64
 1   visitor_id    755405 non-null  str
 2   visit_id      755405 non-null  str
 3   process_step  755405 non-null  str
 4   date_time     755405 non-null  str
dtypes: int64(1), str(4)
memory usage: 81.6 MB

- Missing values

In [16]:
print(df_web.isnull().sum())

client_id       0
visitor_id      0
visit_id        0
process_step    0
date_time       0
dtype: int64

-  Duplicate rows

In [17]:
print("Duplicate rows:", df_web.duplicated().sum())

Duplicate rows: 10764

- Number of unique clients

In [18]:
print("Unique clients:", df_web["client_id"].nunique())

Unique clients: 120157

#### Duplicate Rows Analysis

- Display some duplicated rows

In [30]:
duplicates = df_web[df_web.duplicated(keep=False)]

display(duplicates.sort_values(by=["client_id", "date_time"]).head(10))

,client_id,visitor_id,visit_id,process_step,date_time
631355,1531,934069404_34543643308,110350144_67985219545_904677,start,2017-06-02 22:32:08
631356,1531,934069404_34543643308,110350144_67985219545_904677,start,2017-06-02 22:32:08
631353,1531,934069404_34543643308,110350144_67985219545_904677,start,2017-06-02 22:32:28
631354,1531,934069404_34543643308,110350144_67985219545_904677,start,2017-06-02 22:32:28
639529,2078,585735301_21309149782,900598259_99565669243_552843,start,2017-05-06 08:29:00
639530,2078,585735301_21309149782,900598259_99565669243_552843,start,2017-05-06 08:29:00
639524,2078,585735301_21309149782,900598259_99565669243_552843,start,2017-05-06 08:36:18
639525,2078,585735301_21309149782,900598259_99565669243_552843,start,2017-05-06 08:36:18
639521,2078,585735301_21309149782,900598259_99565669243_552843,start,2017-05-06 08:36:40
639522,2078,585735301_21309149782,900598259_99565669243_552843,start,2017-05-06 08:36:40

- Percentage of duplicated rows

In [29]:
duplicates_percentage = df_web.duplicated().sum() / len(df_web) * 100

print(f"Percentage of duplicates: {duplicates_percentage:.2f}%")

Percentage of duplicates: 1.42%

- Creation of a cleaned copy without exact duplicate rows

In [31]:
df_web_clean = df_web.drop_duplicates().copy()

print("Original shape:", df_web.shape)
print("Cleaned shape:", df_web_clean.shape)

Original shape: (755405, 5)
Cleaned shape: (744641, 5)

#### Convertion date_time to datetime

In [33]:
df_web_clean["date_time"] = pd.to_datetime(df_web_clean["date_time"],errors="coerce")

print(df_web_clean["date_time"].dtype)

datetime64[us]

#### Final Dataset

In [34]:
df_web_clean

,client_id,visitor_id,visit_id,process_step,date_time
0,9988021,580560515_7732621733,781255054_21935453173_531117,step_3,2017-04-17 15:27:07
1,9988021,580560515_7732621733,781255054_21935453173_531117,step_2,2017-04-17 15:26:51
2,9988021,580560515_7732621733,781255054_21935453173_531117,step_3,2017-04-17 15:19:22
3,9988021,580560515_7732621733,781255054_21935453173_531117,step_2,2017-04-17 15:19:13
4,9988021,580560515_7732621733,781255054_21935453173_531117,step_3,2017-04-17 15:18:04
...,...,...,...,...,...
755400,9668240,388766751_9038881013,922267647_3096648104_968866,start,2017-05-24 18:46:10
755401,9668240,388766751_9038881013,922267647_3096648104_968866,start,2017-05-24 18:45:29
755402,9668240,388766751_9038881013,922267647_3096648104_968866,step_1,2017-05-24 18:44:51
755403,9668240,388766751_9038881013,922267647_3096648104_968866,start,2017-05-24 18:44:34
755404,674799,947159805_81558194550,86152093_47511127657_716022,start,2017-06-03 12:17:09

In [37]:
print("Unique clients:", df_web_clean["client_id"].nunique())
print("Unique visitors:", df_web_clean["visitor_id"].nunique())
print("Unique visits:", df_web_clean["visit_id"].nunique())

Unique clients: 120157
Unique visitors: 130236
Unique visits: 158095

In [38]:
df_web_clean["process_step"].value_counts()

process_step
start      234999
step_1     162797
step_2     132750
step_3     111589
confirm    102506
Name: count, dtype: int64